# Generated by Django 5.2.11 on 2026-03-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordersettlement',
            table='meesho_order_settlements',
        ),
    ]
