# Generated by Django 5.2.11 on 2026-04-04 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0002_alter_ordersettlement_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersettlement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='ordersettlement',
            unique_together={('order', 'transaction_id')},
        ),
    ]
