# Generated by Django 5.2.11 on 2026-04-07 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_ordersettlement_order_and_more'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersettlement',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='platforms.platform'),
        ),
        migrations.AlterModelTable(
            name='ordersettlement',
            table='order_settlements',
        ),
    ]
