# Generated by Django 5.2.11 on 2026-04-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_ordersettlement_platform_alter_ordersettlement_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersettlement',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
