# Generated by Django 5.2.11 on 2026-04-25 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_type'),
        ('payments', '0005_ordersettlement_extra_data'),
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordersettlement',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='ordersettlement',
            index=models.Index(fields=['order'], name='order_settl_order_i_807136_idx'),
        ),
        migrations.AddIndex(
            model_name='ordersettlement',
            index=models.Index(fields=['transaction_id'], name='order_settl_transac_6bd4d3_idx'),
        ),
    ]
