# Generated by Django 5.2.11 on 2026-04-27 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_type'),
        ('payments', '0006_alter_ordersettlement_unique_together_and_more'),
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersettlement',
            name='claim_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ordersettlement',
            name='commission_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ordersettlement',
            name='is_claim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersettlement',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersettlement',
            name='is_rto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordersettlement',
            name='return_shipping_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ordersettlement',
            name='shipping_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordersettlement',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='ordersettlement',
            index=models.Index(fields=['payment_date'], name='order_settl_payment_24aaf8_idx'),
        ),
    ]
