# Generated by Django 5.2.11 on 2026-05-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20260502_1928'),
    ]

    operations = [
    ]
