# Generated by Django 5.2.11 on 2026-05-14 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_accountlock_loginattempt_refreshtoken_sessionlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaChallenge',
            fields=[
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'captcha_challenges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='captcha_cha_expires_a443f6_idx'), models.Index(fields=['ip_address'], name='captcha_cha_ip_addr_14beef_idx')],
            },
        ),
    ]
