# Generated by Django 5.2.11 on 2026-06-20 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('users', '0005_captchachallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='roles.role'),
        ),
    ]
