# Generated by Django 5.2.11 on 2026-07-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='reason',
            field=models.CharField(choices=[('success', 'Successful Login'), ('invalid_creds', 'Invalid Credentials'), ('account_inactive', 'Account Inactive'), ('account_locked', 'Account Locked'), ('invalid_email', 'Invalid Email'), ('signup_attempt', 'Signup Attempt')], default='invalid_creds', max_length=50),
        ),
    ]
