# Generated by Django 5.2.11 on 2026-06-08 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_order_payment_type'),
        ('payments', '0007_ordersettlement_claim_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=120)),
                ('quantity', models.IntegerField(default=1)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rto_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('warehousing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('return_shipping_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('claim_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('roi_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_loss', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit', to='orders.order')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profits', to='payments.ordersettlement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_profit',
                'indexes': [models.Index(fields=['net_profit'], name='order_profi_net_pro_898c8b_idx'), models.Index(fields=['is_loss'], name='order_profi_is_loss_22be02_idx')],
            },
        ),
    ]
