# Generated by Django 5.2.11 on 2026-07-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0002_orderprofit_sku_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderprofit',
            new_name='order_profi_sku_38f402_idx',
            old_name='order_profit_sku_idx',
        ),
    ]
