# Generated by Django 5.2.11 on 2026-03-31 18:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_biodata', '0001_initial'),
        ('marriage_user_auth', '0004_remove_user_created_at_remove_user_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'templates',
            },
        ),
        migrations.AddField(
            model_name='biodata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='biodata/photos/'),
        ),
        migrations.AlterModelTable(
            name='biodata',
            table='biodata',
        ),
        migrations.AddField(
            model_name='biodata',
            name='template',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='marriage_biodata.template'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='biodata',
            unique_together={('user', 'template')},
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='template_id',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='updated_by',
        ),
    ]
