# Generated by Django 5.2.11 on 2026-04-01 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_biodata', '0002_template_biodata_photo_alter_biodata_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marriage_biodata.template'),
        ),
    ]
