# Generated by Django 5.2.11 on 2026-04-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriageuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
