# Generated by Django 5.2.11 on 2026-03-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_user_auth', '0002_user_firstname_user_lastname_user_middlename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
