# Generated by Django 5.2.11 on 2026-03-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_user_auth', '0003_remove_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_by',
        ),
    ]
