# Generated by Django 5.2.11 on 2026-03-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marriage_biodata', '0002_template_biodata_photo_alter_biodata_table_and_more'),
        ('marriage_user_auth', '0004_remove_user_created_at_remove_user_created_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MarriageUser',
        ),
    ]
