# Generated by Django 5.2.11 on 2026-05-12 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chathistory',
            new_name='ai_chat_his_user_id_f16325_idx',
            old_name='ai_chathis_user_id_7deeaa_idx',
        ),
        migrations.RenameIndex(
            model_name='chathistory',
            new_name='ai_chat_his_platfor_c9333e_idx',
            old_name='ai_chathis_platform_3d4e3d_idx',
        ),
        migrations.RenameIndex(
            model_name='chathistory',
            new_name='ai_chat_his_created_522f0c_idx',
            old_name='ai_chathis_created_at_03c8be_idx',
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
