# Generated by Django 5.2.11 on 2026-04-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status_updated_at_and_more'),
        ('products', '0006_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.productvariant'),
        ),
    ]
