# Generated by Django 5.2.11 on 2026-04-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'COD'), ('PREPAID', 'PREPAID')], default='PREPAID', max_length=20),
        ),
    ]
