# Generated by Django 5.2.11 on 2026-06-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_price_at_order',
            field=models.FloatField(default=0, help_text='Cost price captured when the order was created'),
        ),
    ]
