# Generated by Django 5.2.11 on 2026-06-11 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=100)),
                ('deduction_duration', models.DateField(blank=True, null=True)),
                ('deduction_date', models.DateField(blank=True, null=True)),
                ('ad_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ad_cost_after_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ads_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.platform')),
            ],
            options={
                'db_table': 'ads_spend',
            },
        ),
    ]
