# Generated by Django 5.2.11 on 2026-06-20 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsSpend', '0001_initial'),
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adsspend',
            constraint=models.UniqueConstraint(fields=('platform', 'campaign_id', 'deduction_duration'), name='unique_ads_spend_entry'),
        ),
    ]
