# Generated by Django 5.2.11 on 2026-03-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_commission_percent_product_gst_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='rto_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='shipping_cost',
            field=models.FloatField(default=0),
        ),
    ]
