# Generated by Django 5.2.11 on 2026-03-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_rto_cost_productvariant_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=50),
        ),
    ]
