# Generated by Django 5.2.11 on 2026-04-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'sku', 'size', 'color')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku', 'size', 'color'], name='product_var_sku_bc09fb_idx'),
        ),
    ]
