# Generated by Django 5.2.11 on 2026-06-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_costpriceupdatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='requires_manual_review',
            field=models.BooleanField(default=False),
        ),
    ]
