# Generated by Django 5.2.11 on 2026-06-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='costpriceupdatehistory',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
