# Generated by Django 5.2.11 on 2026-06-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_costpriceupdatehistory_effective_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='cost_price_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
