# Generated by Django 5.2.11 on 2026-07-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productvariant_cost_price_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
