# Generated by Django 5.2.11 on 2026-07-29 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('platforms', '0001_initial'),
        ('products', '0012_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['owner', 'is_active', '-id'], name='products_owner_active_id_idx'),
        ),
    ]
